// https://material-ui.com/demos/expansion-panels/#controlled-accordion
import Typography from '@material-ui/core/Typography';
import { FAQPageJsonLd } from 'next-seo';
import React, { Fragment } from 'react';
import FaqItem from './FaqItem';

const FAQAccordion = () => {
  const faqs = [
    {
      questionName: 'What is the Steem Blockchain?',
      acceptedAnswerText:
        "A blockchain is a public, immutable, decentralized and censorship-resistant way of storing data secured by cryptography. Steem is a social blockchain that grows communities and makesimmediate revenue streams possible for users by rewarding them forsharing content. Visit <a href='https://steem.com/' rel='noopener noreferrer nofollow' target='_blank'>steem.com</a> for more information.",
    },
    {
      questionName: 'What are MILES tokens?',
      acceptedAnswerText:
        'MILES tokens are a planned cryptocurrency token (SMT) operating on the Steem Blockchain with functionality similar to STEEM, but with a rewards pool exclusively for TravelFeed posts. On top of earning more curation rewards and giving an account more influence over the MILES rewards pool, staking MILES tokens will give users access to several Premium features and additional revenue streams on TravelFeed. We will release more information on MILES in Q1 2020. We plan on rewarding past, current and future TravelFeed users and delegators by airdropping MILES to them, but we believe in building our platform first and with it a MILES economy deeply integrated into the platform, instead of launching a worthless token without a use case now.',
    },
    {
      questionName: 'Where does the money come from?',
      acceptedAnswerText:
        'STEEM, and in the future the TravelFeed MILES tokens, are inflationary currencies with a yearly inflation of currently around 10%. A large part of the new STEEM tokens generated by inflation goes towards the rewards pool that is distributed among content creators and curators by giving smiles.',
    },
    {
      questionName: 'What are smiles?',
      acceptedAnswerText:
        'On TravelFeed, you can upvote posts and comments by pressing the vote button and moving it. We call that giving smiles. You can give up to 10 smiles per post, equaling a 100% upvote on Steem. The more smiles you give, the less powerful they are, but your fuel tank recharges by 100 smiles every day. The more smiles are given to a post, the more visibility it will get and the higher the reward that the author will get from the rewards pool. The rewards for a post are not only determined by the total amount of smiles received, but also by the influence (currently determined by Steem Power held) of each curator — one smile by a powerful account like @travelfeed can be worth more than ten smiles from a small account.',
    },
    {
      questionName: 'What is a curator?',
      acceptedAnswerText:
        'A curator is anyone voting on TravelFeed posts, including yourself. By giving smiles to a post before it goes viral, you can earn curation rewards from the rewards pool, potentially higher than the value of your vote. A TravelFeed curator is part of our team and controls smiles given by the account @travelfeed.',
    },
    {
      questionName: 'How can I get smiles from @travelfeed?',
      acceptedAnswerText:
        'We operate a team of professional curators. Every day, we read all posts submitted to TravelFeed. Up  to five posts are featured on the front page and receive 10 smiles, smaller smiles are distributed to all other submissions.',
    },
    {
      questionName: 'What are the quality requirements for posts?',
      acceptedAnswerText:
        'If you want to post your blogs on TravelFeed, please make sure that your post fits our criteria:<ul><li>Only original content;</li><li>You must post in the language selected, without the use of translation tools;</li><li>At least 250 words in English;</li><li>Proper sourcing if you are using any media that are not your own;</li><li>No copyright violations;</li><li>Only travel-related content.</li><li>Your post must not be a repost of your previous TravelFeed posts</li></ul>',
    },
    {
      questionName:
        'Can I participate in TravelFeed from other Steem frontends?',
      acceptedAnswerText:
        'As long as your Steem post contains the tag #travelfeed and meets our criteria, it will be visible on TravelFeed and eligible for curation. However, we recommend using TravelFeed.io to author your posts to make use of our unique features, such as the location picker within the editor. Only TravelFeed.io posts receive a <em>TravelFeed.io Original</em> star, double smiles and a chance to be featured in our round-up posts.',
    },
    {
      questionName: 'Does TravelFeed charge beneficiary rewards?',
      acceptedAnswerText:
        "We don't take anything from your hard-earned rewards and will never set any beneficiaries without your consent. You can set custom beneficiaries to your liking when publishing posts.",
    },
  ];
  return (
    <Fragment>
      <FAQPageJsonLd mainEntity={faqs} />
      <div>
        {faqs.map(item => {
          return (
            <FaqItem
              title={item.questionName}
              content={item.acceptedAnswerText}
            />
          );
        })}
      </div>
      <Typography gutterBottom variant="h5" className="pt-4">
        More Questions?
      </Typography>
      <p>
        We are happy to answer your questions and add them to the FAQ! You can
        contact us:
      </p>
      <ul>
        <li>
          By email:{' '}
          <a
            href="mailto:contact@travelfeed.io"
            rel="noopener noreferrer nofollow"
            target="_blank"
          >
            contact@travelfeed.io
          </a>
        </li>
        <li>
          By visiting our Discord:{' '}
          <a
            href="https://discord.gg/jWWu73H"
            rel="noopener noreferrer nofollow"
            target="_blank"
          >
            https://discord.gg/jWWu73H
          </a>
        </li>
      </ul>
    </Fragment>
  );
};

export default FAQAccordion;
